### ISSUE TITLE
Use clang-cl driver by default 

### ISSUE THREAD

**Issue by zjturner** [Caphyon/clang-power-tools#1]
Hi, i work on clang for Windows.  Found out about this via Victor’s talk.  I told him this in person but I’m putting it here so it doesn’t get forgotten.

Clang on windows is generally expected to be invoked as `clang-cl.exe`, but the extension uses `clang++.exe`.  It’s possible to make this work, as you’ve discovered, but there’s several surprising issues that can arise, so I’m not sure it’s the right “default” experience.

For starters, it will be harder to get your code to even compile at all because there are a lot of special options that you need to pass to get it into ms compatibility mode with the right paths.  But worse, you may end up checking different code than you’re actually building because you’re not using the same options your build system uses.  This puts a large burden on the user to make sure they understand how to translate msvc compilation flags to clang compilation flags.

Since you’re already hooking into the vcxproj, you can determine on a per file basis the exact msvc style command line, this way you guarantee you are checking the same code you are shipping.

Of course, you can still provide options to override this or add clang specific command line options, but it seems like this should be “advanced” and not the default experience.

A couple of things you might not know that could help:

1. If you run `clang-cl.exe` you literally pass the exact same command line as you would to `cl.exe`.  But if you add `-###` at the end, instead of compiling, it will show you the “real” command line being generated.  Perhaps the system could use this intelligently as a starting point.

2. You can still pass most (all?) clang dash-options to `clang-cl.exe` and even mix msvc slash options with clang dash options.

3.  `clang++.exe` is a synonym for `clang.exe —driver-mode=g++` and `clang-cl.exe` is a synonym for `clang.exe —driver-mode=cl`

In any case, I encourage you to look into defaulting to using the cl driver as I think it will be more familiar to users and in most cases will allow everything to “just work” immediately out of the box without having to futz around with clang command lines

**Comment by cpp-red-lion** [comment]
Very informative feedback. Thanks, Zachary.
Will definitely consider `clang-cl.exe` driver as an alternative for the VS extension, in a future version.

We were reluctant to use the `clang-cl.exe` driver because it is **too** compatible with `cl.exe`, emulating its bad behaviors in terms of ISO C++ conformance (by automatically suppressing too many warnings).
We wanted to retain full controls over the clang error flags, so that we can gradually eliminate all non-standard source code constructs. While this was annoying at first (lots of warnings), we found great benefits from actually **fixing** those warnings, instead of suppressing them. 

I do agree, however, that for some teams this could be very challenging and a more `cl.exe` compatible option should be required. For this purpose, we now default to the following `clang++` flags:
- -std=c++14
- -Wall
- -fms-compatibility-version=19.10
- -fms-compatibility
- -Wmicrosoft
- -Wno-invalid-token-paste
- -Wno-unknown-pragmas
- -Wno-unused-variable
- -Wno-unused-value

**Comment by zjturner** [comment]
Yea, definitely understand about wanting to be more conformant.

This is probably reasonable, the main thing I was concerned about is that people wouldn't be able to use it without going and learning a bunch of clang flags, which might be offputting for someone who wants an out-of-the-box experience that just works immediately after installing.  As long as it "just works" with reasonable defaults then I'm happy :)

**Comment by Enache-Ionut** [comment]
How this issue is solved I will close it now. 

Thank you for taking the time and helping us make a better product.
