### ISSUE TITLE
Cannot use clang-power-tools on .cu files

### ISSUE THREAD

**Issue by EricCreusen** [Caphyon/clang-power-tools#1051]
### Versions used:
Windows 10
Visual Studio 2017
Clang Power tools 7.9.0
LLVM 11.0.0

### Steps to reproduce
A solution containing both .cpp, .hpp and .cu files. Right click a .cu file and try to use clang-power tools.

### Expected result
Clang power tools options available as usual

### Actual result
Clang power tools options greyed out (except for settings menu)

### Workaround
Rename .cu file to .cpp, use clang power tools, rename back.

### Relevant clang power tools settings
Tidy->Header Filter = ".*"
Format->File extensions = ".c;.cpp;.cxx;.cc;.cs;.tli;.tlh;.h;.hh;.hpp;.hxx;.cu"

**Comment by hero101111** [comment]
Hello @EricCreusen 

Thank you for submitting this issue. We've reproduced it and will provide a fix for it as soon as possible. 
Please know that if you're using the command line, via our `clang-build.ps1` PowerShell script, this issue is not present, everything will work. 
Only when using Clang Power Tools directly from Visual Studio, there is a problem and your workaround is needed, for the time being.

Regards,
Gabriel.
