### ISSUE TITLE
No output during compile

### ISSUE THREAD

**Issue by pasa-** [Caphyon/clang-power-tools#1209]
After one of the recent updates the output window only shows compile started and finished (unless verbose is on). 
It used to show the names of files. 

Also, there used to be a raw version of the warnings output, now it only appears in the error list pane. 

Those outputs were useful for regular workflow, please bring them back.

**Comment by mariru27** [comment]
Hi @pasa- ,

Thank you for reporting this issue
I can reproduce the problem, we will return to the previous behavior in a short time

Have a nice day

**Comment by mariru27** [comment]
Hi @pasa- ,

A fix for this issue is available in release [v9.4.2](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools#:~:text=Clang%20Power%20Tools%20is%20a,with%20its%20static%20analyzer%20and)
Can you update Clang Power Tools to v9.4.2 and tell us if the problem is still reproducing?

Best regards,
Marina
