### ISSUE TITLE
Format on save does not work in VS 2022 17.7.0

### ISSUE THREAD

**Issue by magnesj** [Caphyon/clang-power-tools#1310]
**Environment**
VS 2022 17.7.0
Clang Powertools 2023.7.0

**Descriptions**
Format on save does not work in VS 2022 17.7.0
Pushing the format button on the toolbar works as expected.

![image](https://github.com/Caphyon/clang-power-tools/assets/1793152/81c737fe-60d9-4da7-b87e-4c3274df42e4)

**Comment by Tyranisaur** [comment]
For what it's worth, considering adding a vote here https://developercommunity.visualstudio.com/t/Add-option-to-trigger-C-clang-format-o/1461356 because having this built in to Visual Studio itself is probably both what everyone wants and should lead to less breakage of the feature.

Also, while I'm here, this also doesn't work in Visual Studio 2022 17.8.0 Preview 1.0

**Comment by serkanergun** [comment]
I recently upgraded to 17.7.0 and I noticed the same issue. Could'nt find a workaround so far.

**Comment by mariru27** [comment]
Hi @magnesj, @Tyranisaur, @serkanergun,

Apologies for the delayed response. We have identified the issue and are actively working on a solution. A release containing the bug fix will be made available shortly.

Thank you for letting us know about this issue

Best regards,
Marina

**Comment by magnesj** [comment]
Thanks, I appreciate the quick feedback. Thanks for providing a very useful tool.
