### ISSUE TITLE
Is there a way to kill "release notes" pop up?

### ISSUE THREAD

**Issue by pps83** [Caphyon/clang-power-tools#1358]
I installed clang power tools vs extension, but I rarely use it. However, it constantly reminds me of it:

![image](https://github.com/Caphyon/clang-power-tools/assets/1614246/82a9d409-50de-48ec-a398-f68f36da0de9)

This popup is extremely annoying, it doesn't show up just once, it seems that it randomly shows up from time to time.
I have `vs2022` and `vs2022 preview` installed. Perhaps, because there are two versions of vs2022 it somehow gets confused.

Anyways, I'd rather completely disable that popup. Is there such option?

**Comment by mariru27** [comment]
Hi @pps83,

The issue with the popup is likely due to having both VS2022 and VS2022 Preview installed. For the best results, ensure that the Clang Power Tools extension is updated to the same version across all your Visual Studio installations. Please upgrade to the latest version of Clang Power Tools to help resolve the problem.

Best regards,
Marina
