### ISSUE TITLE
Export/import configuration of Clang Power Tools

### ISSUE THREAD

**Issue by jcageman** [Caphyon/clang-power-tools#167]
If we could import & export the configuration of powertools its easier to share within a team to ensure the same configuration is used. Do you know of any way how to do this currently or is it on the todo list for the future?

**Comment by cpp-red-lion** [comment]
Hi,

We have thought about this issue, but we're not yet _committed_ on a design:
-  should the settings remain global ? 
- should we allow them to be customized per solution/project ?
- should we offer import/export ?
- should we save them relative to the VS solution, so that you can commit the config file to SCM ?
- etc.

In the meantime, until we reach a good/flexible design and implement UI for it, you can find the settings stored in this folder:  `%AppData%\ClangPowerTools`

**Comment by jwtowner** [comment]
I think making the configuration options overridable on a per-project basis makes the most sense for existing projects with lots of code. It would allow us to incrementally migrate old code to new language standards and higher levels of clang-tidy conformance over time. The global user configuration could still be used as a fallback.

This could be implemented with custom MSBuild properties in the .vcxproj files or imported .props files. For solution-wide properties, a Directory.Build.props file or an explicitly imported .props file could be used. That way there is no need to have separate files for per-project Clang Power Tools configuration.

**Comment by cpp-red-lion** [comment]
Interesting suggestion, @jwtowner 👍 
We'll look into that.

**Comment by Enache-Ionut** [comment]
Hi,

We are happy to announce the release of [Clang Power Tools version 5.1](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools). This issue was fixed so please check for updates.

Thank you for your feedback 😃
