### ISSUE TITLE
VS complains about wrong line endings after tidy

### ISSUE THREAD

**Issue by s-martin** [Caphyon/clang-power-tools#170]
When I run Tidy with Fix enabled, VS2017 complains on changed files afterwards that the line ending is not consistent and suggests CRLF.

I assume tidy uses Unix (LF) line endings, but could this be made consistent to the used line endings or be configurable?

**Comment by cpp-red-lion** [comment]
> I assume tidy uses Unix (LF) line endings ... 

Not all clang-tidy checks do this; for example, `modernize-*` checks don't, but some `readability-*` checks do add `LF` instead of `CR LF`  :(

As far as I know, clang-tidy doesn't support _configuring_ line endings for auto-fixes.

In our team, we use `clang-format` after tidy and this automatically fixes all the line endings for us.
This support is coming soon in Clang Power Tools ( #67 ) as a built-in feature.

**Comment by mrexodia** [comment]
Maybe it could be an idea to temporarily add a step to normalize line endings inside the extension itself?

**Comment by s-martin** [comment]
If `clang-format` fixes this, I'm fine with that.

**Comment by Enache-Ionut** [comment]
Hi,

This issue was fixed using clang-format and it will be available in the next version. 
Thank you for your feedback !
