### ISSUE TITLE
Specify clang path

### ISSUE THREAD

**Issue by mbrucher** [Caphyon/clang-power-tools#199]
In some environments, users can't add clang to PATH. With a configuration option, people could be using the tool.

**Comment by cpp-red-lion** [comment]
Hi,

It's not mandatory to add **Clang** to the SYSTEM `%PATH%`

If you installed LLVM to the default location (eg. "C:\Program Files\LLVM") no configuration is needed. It will automatically be detected.

You can also add your "LLVM\bin" folder to **per-user** `%Path%` environment variable.
(same Windows configuration dialog box)

**Comment by mbrucher** [comment]
That's the same issue, one may not be able to install anything in a system folder without admin privileges (that's my case), or even open the advanced settings control boc.

**Comment by cpp-red-lion** [comment]
_Change environment variables as standard user_ (no admin rights):
https://superuser.com/questions/25037/change-environment-variables-as-standard-user

You can also add your "LLVM\bin" folder to **per-user** `%Path%` environment variable.

**Comment by cpp-red-lion** [comment]
Hi @mbrucher ,

Did my last comment/link solved your problem ?

**Comment by mbrucher** [comment]
Sorry, wasn't available to answer yesterday.
Yes, that works. I still think that allowing people to select the clang folder from the property windows is a good feature.

**Comment by cpp-red-lion** [comment]
I'll leave this issue open, then.

**Comment by InfiniteStateMachine** [comment]
Hi @cpp-red-lion,
I can take a look at this if you don't mind.

**Comment by hero101111** [comment]
Hey,

Happy to see this issue is progressing.
Kudos to @InfiniteStateMachine for taking the time to draft an implementation (#270).

We'd like to hear more of your input regarding the rationale for bringing to life this configuration option.
As @cpp-red-lion has stated before, the `system or user PATH` environment variable can be used to set a custom path to a clang/llvm toolset. 
Looks to me we are not dealing with enabling a scenario that's currently impossible, this is a usability issue.
Any scenarios we've missed where a new configuration option would enable something that's currently not possible?

The `PATH` environment variable is a universal mechanism for discovering tools and EXEs on Windows. We went along this path (_pun intended_), alongside detecting usual _ProgramFiles_ install locations, because we want to keep things simple for the majority of users, for ClangPowerTools to _just work_.
Meanwhile developers with more complex environments would be able to use the standard `PATH` mechanism, without us exposing a potentially confusing option to each and every user.

It would be helpful to know if you outright expected a dedicated UI option for configuring the clang location. If so, did you expect ClangPowerTools to work straight out-of-the-box without setting this option? What would be an appropriate default value?

**Comment by InfiniteStateMachine** [comment]
Heyall,

You're welcome! I'm watching this space before I'll push more changes.

I have a question too, regarding the update of the %PATH% when the Clang bin directory is found. More exactly it's this line: `$env:Path += ";$locationLLVM"` from the PowerShell script.

I am wondering what was the rationale behind this update. For DLLs, https://msdn.microsoft.com/en-us/library/ms682586.aspx states that these are loaded from the application directory. But if the executables started by the PowerShell script spawn others from the same directory (#1) then the value of the %PATH% variable may influence this process. Is this the reason for updating it?

Do you think that *prepending* the custom path to a %PATH% already pointing to the Clang binaries is a proper override?

**Comment by mbrucher** [comment]
I would say that it could be nice to have the path to the detected clang-tidy in the option window. If the user overrides it, then use the overriden path.
At least that's what I would expect to specify the tool.

Thanks for tackling this!

**Comment by hero101111** [comment]
@InfiniteStateMachine We originally relied on the `PATH` environment variable to contain the LLVM install path, in our PS code we simply invoked clang++ when needed. 

It then came to our attention that a great deal of users may _not_ add the LLVM installation path to `PATH` during install since that checkbox is unchecked by default. That would have left ClangPowerTools in a non-working state out-of-the-box. 

We decided to manually append the LLVM install location (if we detect any) to `PATH` in order for ClangPowerTools to work _OOTB_ on those machines while keeping our existing code intact.
The `PATH` update is volatile and limited to the current working process which seemed ideal.

Prepending the custom path to `PATH` should do the job of overriding existing paths.

Regards,
Gabriel

**Comment by InfiniteStateMachine** [comment]
Thanks Gabriel for the clarification.

I guess we'll go with a new property and implement the algorithm from PowerShell in C#: 
- check the `%PATH%`, and then `%ProgramW6432%\LLVM\bin` + `%ProgramFiles(x86)%\LLVM\bin`. 
- override if a custom path is input by the user; send it via a new PowerShell parameter and _prepend_ it to the PowerShell process (+ children) `%PATH%`.

Should we keep the detection algorithm in the PowerShell script? If the executable is not detected in the system `%PATH%` but is detected in the standard installation directories, I could still send the detected path via the same PowerShell parameter. People using the script directly might be affected by this removal.
