### ISSUE TITLE
Add a feature to ignore a path

### ISSUE THREAD

**Issue by aliha** [Caphyon/clang-power-tools#281]
Example: Ignore all files in "3rdparty" sub-directory

**Comment by cpp-red-lion** [comment]
Hi,

Thank you for your suggestion 👍

**Comment by kpiekara** [comment]
Is this planned to be implemented? I wonder if there is any other way to suppress warnings/errors from external directories eg. boost directory or library headers?

**Comment by cpp-red-lion** [comment]
Currently, this improvement is not high priority.

As a (partial) workaround, we do have support (_Settings_) for `Files to ignore` and `Projects to ignore`.  
Both support regex matching and lists of items.

As for `clang-tidy`, a workaround might be to use the `Header filter` setting we support.

**Comment by kpiekara** [comment]
Regex for `Files to ignore` is applied only to file names or to whole file path?

**Comment by cpp-red-lion** [comment]
Just file names, not directories.

**Comment by cpp-red-lion** [comment]
@dmateja : Not sure a separate config file `_clang-power-tools` is the way to go here...
In order to be consistent with the other filter like settings (ignored files, ignored projects), we should make it a _Clang Power Tools_ setting. These are implemented in the VS extension and passed to the PowerShell script via command line parameters.

As for the fact that, for the moment, these settings are **global**, we have a separate issue for that, with an interesting suggestion to override them at _project level_.
See this comment:  
https://github.com/Caphyon/clang-power-tools/issues/167#issuecomment-375784838

**Comment by dmateja** [comment]
@cpp-red-lion Hmmm... I work with dozens of projects, so separate 'global' config is very useful for me. Most of these projects have similar a code structure. With separate global config I don't need to edit all of the projects to add proper 'props' file. One global config in Visual is also not good for me - I need several common configurations for groups of the projects.
I have to think about 'props' files... maybe...

**Comment by jwtowner** [comment]
Hi @dmateja using .props files to centralize any new ClangPowerTools centric MSBuild properties so that they could be shared by all projects in a solution, or by multiple solutions, would likely serve your interests while still supporting further use cases needed by others. It's no different than using property sheets to share the same compiler and linker settings across multiple projects.

At our business, we run multiple product teams that consume shared libraries out of different branches, and it can sometimes be a few months before one product team is able to sync up with the latest stable code release due to certain external dependencies. Since certain projects remain in a frozen state, we really need per-project ClangPowerTools configurations to ease our migration strategy.

**Comment by cpp-red-lion** [comment]
Hi @jwtowner ,

You make a good point, there.

It's tough to please everyone, because the configuration and project needs are so very different...
That's why, when it comes to this sensitive issue (_configs_), we didn't rush into it.

**Comment by hero101111** [comment]
Hello,

Happy to inform you that, as of version `4.0`, the bulk-ignore functionality is implemented.
To ignore all files in a directory simply specify the directory name in the `file-ignore` parameter.

`CPT v4.0` has also introduced support for [configuration files](https://github.com/Caphyon/clang-power-tools/blob/master/ClangPowerTools/ClangPowerTools/cpt.config) which allow for CPT configuration sharing across multiple projects.

Regards,
Gabriel.

**Comment by taeguk** [comment]
@hero101111 `file-ignore` is just for cpp files. I need the way to ignore **third-party header files**. How about adding an option which indicates paths that will be passed to `clang-tidy` with `-isystem`.

**Comment by hero101111** [comment]
Hello,

As of CPT 4.10 `-file-ignore` supports both cpps _and_ headers.
I don’t understand exactly what you mean regarding `clang-tidy / isystem`. Please go into more detail.

**Comment by aliha** [comment]
Has anyone figured it out how to ignore all **third-party header files** in a "third-party" subdirectory?
What string should I add to "File to ignore"?

**Comment by hero101111** [comment]
Hello @aliha ,

The `Files to ignore` mechanism is for ignoring your own files, not third-party library files.

What you want to do is any of the following: 
`1.` In your Visual Studio project properties, move the third-party include directory to `VC++ Directories > Include Directories` instead of `C/C++ > Additional Include Directories`
`2.` From Clang Power Tools settings, set `Treat additional include directories` to _System include directories_

Let me know if this helped.

Regards,
Gabriel.

**Comment by aliha** [comment]
Thank you @hero101111 .
That might be a temporary/manual solution for me.
But, since most of the projects I work on are generated using cmake, manual changing of them is not a practical option. 
Also, what if I want to exclude a sub-module, with headers and source files, stored in a subdirectory?
