### ISSUE TITLE
do not implicitly decay an array into a pointer.

### ISSUE THREAD

**Issue by Donaldpherman** [Caphyon/clang-power-tools#382]
Warning Clang : do not implicitly decay an array into a pointer; consider using gsl::array_view or an explicit cast instead.

m_pCmdLine = new CCommandLine(m_lpCmdLine); // warning

// CCommandLine Headerfile
CCommandLine(LPTSTR lpCmdLine)
I run clang as a check on an MFC project I work on. Why does it give me a warning when making a copy of a Long Pointer to a TStr? What explicit cast does it wants from me to fix this warning?

**Comment by cpp-red-lion** [comment]
Hi,

Thank you for your interest in _Clang Power Tools_.

This appears to be a legitimate _warning_ in your code, rather than a Clang Power Tools issue.  
Clang compiler tends to be much more strict about ISO C++ language rules than MSVC, so these kind of warnings are inevitable when switching to Clang.

If you want some help solving this particular warning, please provide more context (types of variables involved).
