### ISSUE TITLE
Option 'Tidy' no longer shows clang compiler warnings

### ISSUE THREAD

**Issue by Arminius** [Caphyon/clang-power-tools#387]
In previous versions of Clang Power Tools, clicking on 'Tidy' would show both compiler warnings given by clang as well as the output of clang-tidy. As far as I can see, this is no longer the case. Why is that?

The compiler warnings are pretty useful, I liked being able to see both the compiler output and the clang-tidy output at once. Now I have to click both 'Tidy' and 'Compile (syntax only)' to get the output I want.

**Comment by Philippe91** [comment]
I think it is better now, hence I hope a change would be optional.
tidy is one thing, the compiler another one.

**Comment by PeterFeicht** [comment]
You could enable the `clang-diagnostic-*` checks in your clang-tidy config, that would do the same I guess.

**Comment by Enache-Ionut** [comment]
Hi, 

We don't apply any filter on **LLVM/Clang output**, but the new behavior can be caused by a **LLVM upgrade**. Please tell us if you changed the **LLVM version** on your machine and specify the current version you are running.
If the LLVM version has not been changed a **sample project** it will be a great help for us.
