### ISSUE TITLE
Clang Power Tools v4.1 : clang-tidy-fix - Errors if parallel is enabled

### ISSUE THREAD

**Issue by magnesj** [Caphyon/clang-power-tools#440]
Thanks for a wonderful tool.

I use the script `clang-build.ps1` with command line parameter `-tidy-fix` active to do some code changes on a code base with close to 1000 files. I use the flag `modernize-use-override`, resulting in source code changes in more than 600 files. When I run using the parallel flag, some of the source files are obfuscated. If run the script in non-parallel mode, everything is fine.

My environment in Visual Studio 2017 15.8.7 and Clang Power Tools v4.1.

**Comment by cpp-red-lion** [comment]
Hi,

We encountered this issue ourselves a few months back.  

Unfortunately, this is a problem with `clang-tidy` itself and how it handles file I/O  
The problem is that clang tooling is designed to operate on _individual_ source files.  

When we parallelize the operation, we just spawn multiple Clang processes to handle individual translation units. This works fine for compilation (fantastic speedup), but it doesn't really work for **clang-tidy** because with `auto-fix` ON it actually changes the input. The problem here are the **shared header files** between multiple source files being processed at the same time.  

We currently don't have a good idea on how to properly handle this combination (clang-tidy + auto-fix + parallel). The only thing that really works for us is to use `-parallel` just for compilation, not for tidy.

If you have suggestions of improving this workflow, feedback/ideas are more than welcomed.
Thanks.

**Comment by magnesj** [comment]
Hi,

Thanks for your feedback.

I would suggest that the `-parallel` flag is ignored when `-tidy-fix` is on, this will at least guard users from getting garbage.

**Comment by hero101111** [comment]
Hello,

We've taken your suggestion into account and starting from Clang Power Tools `v4.2` parallel compilation will be unavailable for `Tidy-Fix`

Thanks for the feedback.
Regards,
Gabriel
