### ISSUE TITLE
Config options are not displayed properly

### ISSUE THREAD

**Issue by Alexolut** [Caphyon/clang-power-tools#563]
I'm using clang-power-tools with VS2017 Community. I've set "Tidy-Use checks from" to ".clang-tidy config file", then go to "Tidy-Custom checks" page and pressed "Ok" button to close the Options dialog. Open settings again, and saw that ""Tidy-Use checks from" is set to default value "predefined checks". It seems that the problem is only with displaying the setting on the settings page, since tidy run actually uses my custom config file. Same issue happens with "Custom executable file" option at least.

**Comment by Enache-Ionut** [comment]
Hi,

We reproduced this issue and we will fix it in the next release of Clang Power Tools. Meanwhile, as a workaround, after you change the settings from an options page you can click OK button. In this way, your changes will be saved. This bug is related to the way of how Visual Studio manipulates its option pages. It saves the changes but just for the current page and unfortunately everything you configured previously will be lost.  

We will update this thread as soon as progress will be made.

Thank you for your feedback.

**Comment by Enache-Ionut** [comment]
Hi,

We are happy to announce the release of [Clang Power Tools version 5.1](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools). This issue was fixed so please check for updates.

Thank you for your feedback 😃
