### ISSUE TITLE
Support for CMake projects

### ISSUE THREAD

**Issue by hprica** [Caphyon/clang-power-tools#605]

**Comment by stevenhoving** [comment]
@hprica what to do for this feature to be implemented?

**Comment by cpp-red-lion** [comment]
Patience grasshopper 😄   
Great things are coming in the pipeline...

**Comment by stevenhoving** [comment]
@cpp-red-lion thanks.... its been a while that I was called a 'grasshopper'. My question actually ment something like this: If somebody would roughly outline what is required to implement this. I would love to have a stab at it.

**Comment by cpp-red-lion** [comment]
@stevenhoving That changes everything. We already have some progress on this front, but we're happy to accept contributions.  
The first thing would be to build a bridge between a CMake project/lists parser and the VS extensibility framework, so that we can extract CMake compilation directives & properties from within the Solution Explorer. 
After that, a middle component would need to translate that CMake payload for each "project" file into a format consumable by our Clang driver.

**Comment by stevenhoving** [comment]
Sorry, but recent changes in the focus of this project forced me to stop working on this issue. Thanks for the advice, and I wish you all the best.

**Comment by Enache-Ionut** [comment]
Hi,

We are happy to announce the release of [Clang Power Tools version 5.1](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools). The CMake support for open file is ready 🎉 

Thank you for your feedback 😃

**Comment by s-martin** [comment]
Are there any conditions, when CPT works with CMake projects?

**Comment by Enache-Ionut** [comment]
Hi @s-martin,

Please be aware that Clang Power Tools is available just on the active file so the commands are activated just in the toolbar for now. 

Can you give us a sample project reproducing the issue for the investigation purpose? The log from the output window will be a great help too.

**Comment by s-martin** [comment]
@Enache-Ionut I'll try that, thanks for the info.
