### ISSUE TITLE
It is possible toselect the files to apply the tidy-fix in VS

### ISSUE THREAD

**Issue by MicheleBe** [Caphyon/clang-power-tools#607]
Hi, I really love the tools tidy and tidy-fix . I found out a small problem with the tool in VS 2017. 
Tools works perfectly but if I ask the tool to automatically fix the fiels it also modify some library cots files (like Boost header) that I can't and I don't want to modify. There is a way to select the files to be analyzed and modified? 
Thanks a lot
Cheers

**Comment by hero101111** [comment]
Hello,

This problem comes down to the way the Boost headers are included in your project.
In order for them to not be touched anymore by tidy-fix you need to do one of the following two:

1. In your Visual Studio project properties, move the Boost directory to `VC++ Directories > Include Directories` instead of `C/C++ > Additional Include Directories`
2. From Clang Power Tools settings, set `Treat additional include directories` to _System include directories_

`1` _or_ `2` should be enough to have tidy-fix behave the way you want.

Let me know if that answered your question.
Regards,
Gabriel
