### ISSUE TITLE
Just updated to 4.10.5 and VS crashes whenever running tidy

### ISSUE THREAD

**Issue by timmmeh** [Caphyon/clang-power-tools#618]
I'm not getting any output before the crash but I captured the VS2017 activity log. It was running fine then I saw the auto update notification now it's crashing.

[Log](https://drive.google.com/open?id=1paxcJ4mafIYgtbrOk8hrenZKtaeIZCOl)

**Comment by Enache-Ionut** [comment]
Hi,

Maybe something went wrong with the auto update system. Just to be sure, please try to make a fresh install. To do this you need to follow the next steps:

1. Uninstall Clang Power Tools from Visual Studio
2. Manually delete the user config files from %AppData%\ClangPowerTools
3. Open Visual Studio and install the Clang Power Tools again 

If the issue is still reproducing after this steps please let me know.

**Comment by timmmeh** [comment]
That did the trick :)

**Comment by Enache-Ionut** [comment]
I'm glad to hear that. Thank you for using Clang Power Tools 😃
