### ISSUE TITLE
Compile & Tidy Crash VS2015 on Version 4.10.5

### ISSUE THREAD

**Issue by matthew17754** [Caphyon/clang-power-tools#625]
Selecting either the _compile_ or _tidy_ options from the toolbar crash Visual Studio 2015.
This occurs when working with an open file (Ctrl+O) a.k.a. non project/solution file.
[ActivityLog.txt](https://github.com/Caphyon/clang-power-tools/files/3318417/ActivityLog.txt)

![ClangPowerToolsCrash](https://user-images.githubusercontent.com/14935352/59980854-35265c80-95b0-11e9-88c7-2e9e7f852188.gif)

**Comment by Enache-Ionut** [comment]
Hi,

We are happy to announce you that in the last version, [v5.0.1](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools),  we fixed this issue on VS2015, please check for updates. 

If the issue is still there let us know. A sample project will be a great help for us. 

Regards,
Ionut
