### ISSUE TITLE
Disable toolbar buttons when not selecting compatable solution item

### ISSUE THREAD

**Issue by contre** [Caphyon/clang-power-tools#637]
When selecting a c# file or a c# project, the toolbar buttons are still enabled allowing me to click them. It doesn't do anything but a simple usability fix would be to disable them for non relevant files/projects. 

Additionally, right clicking on the same incompatible files, shows the Clang Power Tools menu option. My expected behavior would be to not have the Clang Power Tools menu option show up.

**Comment by Enache-Ionut** [comment]
Hi, 

We are aware of this issue. It is on our to-do list for the near future #573. For any other issues that you encounter while using the Clang Power Tools extension please let us know.

Thank you for your feedback! 

Best regards,
Ionut

**Comment by Enache-Ionut** [comment]
Hi,

This issue was fixed and it is available in the fresh release of [Clang Power Tools v5.2](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools). 

Check out the full list of features, improvements, and bug-fixes: https://clangpowertools.com/CHANGELOG.html.

Thank you for your feedback!
