### ISSUE TITLE
When switching windows using Alt + Tab "Settings Input" dialog is getting disappeared in VS 2019

### ISSUE THREAD

**Issue by sonulohani** [Caphyon/clang-power-tools#689]
Steps to reproduce:-
1. Open clang power tools settings.
2. Go to compiler tab
3. Click on three dots(...) button next to either Compile flags, files to ignore or Projects to ignore to open Settings Input dialog. 
4. Press Alt + Tab (Make sure some app is running in the background)
5. Switch again back to clang power tool settings. The Settings Input dialog is gone and the clang power tool setting window is unresponsive.

**Comment by Enache-Ionut** [comment]
Hi, 

We reproduced this issue and we will address it in a future release. Thank you for your feedback. 

Meanwhile the new version of [Clang Power Tools v5.3](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools) was just released. Please check for updates. 

Regards,
~Ionut

**Comment by Enache-Ionut** [comment]
We are glad to announce that this issue is now fixed and it will be available in the next release of Clang Power Tools (v5.4). Thank you for taking the time to report this issue and help us to make a better product.

I want to let you know that any feedback is precious to us, so feel free to share your thoughts about Clang Power Tools with us.

For any other issue, we are here to help.

Regards,
~Ionut
