### ISSUE TITLE
Hpp file issue

### ISSUE THREAD

**Issue by jimmybutler-2015** [Caphyon/clang-power-tools#701]
Hello,
I am going to clang-tidy hpp files using clang-power-tools, but clang-power-tools menu items are disabled when I have opened the menu on the hpp file. Why does this happen?

![image](https://user-images.githubusercontent.com/55069554/68294373-f4486380-00ca-11ea-9f02-4bc43f5d1e75.png)

**Comment by Enache-Ionut** [comment]
Hi, 

Clang commands are not currently available on `.hpp` files. Visual Studio doesn't allow VS compile on this type of file either. To make clang know about your `.hpp` file you can try to execute one of the clang commands (Compile / Tidy) on a `.cpp` file which includes your `.hpp` file.

Regards,
~Ionut

**Comment by jimmybutler-2015** [comment]
I am going to apply "modernize-use-override" to my` .cpp `file and the `.cpp` file includes a .h file, but clang tidy is not applied to `.h` file. It is applied to only `.cpp` file. Can you give me any hint about this?

Header.h

```
class Base
{
public:
	virtual void print() const = 0;
	virtual void printthat() const = 0;
	virtual void printit() const = 0;
};
class inhert : public Base
{
public:
	// only virtual keyword for overriding.
	void print() const override {}

	// only override keyword for overriding.
	virtual void printthat() const {}

	// using both virtual and override keywords for overriding.
	virtual void printit() const {}
};
```

Test.cpp

`#include "Header.h"`

**Comment by Yattabyte** [comment]
Issue still present, however can be circumvented if "Format on Save" is enabled and the header is changed.

**Comment by Enache-Ionut** [comment]
Hi,

Our default for the file processing is set on Proces Header but to be able to take advantage of this your Visual Studio project cannot contain `Include Directories` headers because they will be treated as system library and they will be implicitly ignored.  

You need to change your VS project settings from `Include Directories` to `Additional Include Directories`. Let me know about de result of this action. 

Regards,
~Ionut
