### ISSUE TITLE
Clang Tidy fails with MS headers "Errors encountered during PCH creation"

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#926]
--- CLANG COMPILE STARTED ---

PROJECT: F:\REDACTED\redacted.vcxproj [Debug|x64]
In file included from F:\REDACTED\stdafx.h.hpp:49:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\atlmfc\include\afxwin.h:19:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\atlmfc\include\afx.h:761:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\atlmfc\include\afxstr.h:36:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\atlmfc\include\cstringt.h:32:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\atlmfc\include\atlsimpstr.h:21:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\intrin.h(56): error: expected function body after function declarator
__MACHINE(void * _AddressOfReturnAddress(void))
^
1 error generated.
Errors encountered during PCH creation

--- CLANG COMPILE FINISHED ---

**Comment by hero101111** [comment]
Hi,

Unfortunately this is a regression (bug) in VS 16.8
We hit this, ourselves, too.

It was already fixed in 16.9 Preview 2.
Preview 2 might land in December, but the final version (16.9) will be out in February '21, roughly.

The bug is fully documented here:
https://github.com/microsoft/STL/issues/1300

Although fixed 2+ months ago, unfortunately, it didn't make it into VS 16.8 in time.

Workaround is to manually patch your <intrin0.h> header, like Casey Carter suggested (in the GitHub issue).

I can confirm it works with his patch (we chose this way). I attached the patched version to this email (you need to overwrite it in Program Files).
You can do the same or downgrade VS to 16.7.x

Best regards
[intrin0.h.zip](https://github.com/Caphyon/clang-power-tools/files/5958426/intrin0.h.zip)

**Comment by netx123** [comment]
Thanks for the quick response and workaround.
I've replaced the intrin0.h and its working great now.

**Comment by hero101111** [comment]
I am happy to hear that your problem has been solved. 


Regards,
Gabriel
