### ISSUE TITLE
Ignore folders

### ISSUE THREAD

**Issue by hprica** [Caphyon/clang-power-tools#965]
Add the option to ignore all the files inside of a folder

**Comment by ahamuraru** [comment]
Is there any update on this issue?
I am also looking for a way to specify a list of files or folders to be ignored when running Tidy or Tidy-fix.

**Comment by hero101111** [comment]
Hello @ahamuraru 

As of `v7.9`, Clang Power Tools does not predefined support (visual picker interface) for ignoring particular folders.
However, you can achieve this by using the 'Files to ignore' field. This field supports partial matching of the project file paths, in your case the parent directory path.

E.g. to ignore `C:\source\myproj\main.cpp` you could pass `C:\source\myproj` to the `Files to ignore` field.

**Important note:** there's been a regression introduced by `v7.9` affecting the file ignore mechanism, which we've fixed in the interim. Please make sure to update your Clang Power Tools scripts before trying to use the file-ignore feature.
 You can do that by clicking the `PowerShell scripts [Update]` button in the Visual Studio extension user interface.
 
 Please let us know if these instructions are of help regarding your particular scenario.
 
 Best regards,
 Gabriel.

**Comment by ahamuraru** [comment]
Hi Gabriel,

If I go to VS2017, Tools->Extensions and Updates, I see that Clang Power Tools v7.9.0 is installed. 'Automatically update this extension' is checked, so I think I have the latest version.

I have also went to Clang Power Tools -> Compiler and clicked the 'Update' button for 'PowerShell scripts'.

However, it seems that Tidy and Tidy-fix still ignore the files from 'Files to ignore' list. Am I doing something wrong?

Thanks,
Anca
