### ISSUE TITLE
How to build from source

### ISSUE THREAD

**Issue by timxx** [Caphyon/clang-power-tools#975]
I'm using VS 16.7.7, it loads the solution nicely, but can't build with it.
Part of warnings and errors:

> warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.VisualStudio.CoreUtility, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.VisualStudio.Editor, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a,

> clang-power-tools\ClangPowerTools\ClangPowerTools\Extensions\ObjectExtension.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
> clang-power-tools\ClangPowerTools\ClangPowerTools\MVVM\LicenseValidation\LicenseType.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

I'm pretty new to C# and VS extension development, have no idea how to deal with it.

**Comment by hprica** [comment]
Hello @timxx,
Thank you for using Clang Power Tools. 

The main issue you are having is due to Visual Studio 2015. To properly build the extension you also need to install it first on your machine. There are some dependencies that need to be solved once you install it. 

Support for Visual Studio 2015 will be dropped, this week's release will be the last one with 2015. The entire project will be built the Extension SDK, solving all these dependency issues.  

If you want to use the new project you can get it directly from the branch: https://github.com/Caphyon/clang-power-tools/tree/vs2022-support. 

As a side note, there might be some warnings that were not solved yet on the branch. Let me know if you need any help.

**Comment by timxx** [comment]
It's my fault, but I'm using visual studio 2019 too.
Branch vs2022-support  can compile after all, many thanks

**Comment by hprica** [comment]
@timxx it's not your fault, it's VS2015 fault. 

Glad to hear the branch works 🎉 It will be merged in the coming weeks into master.
